### ISSUE TITLE
Flow tests fail in Release-V3 branch

### ISSUE THREAD

**Issue by ASitnikov** [corda/cordapp-tutorial#159]
Both java and kotlin flow tests fail with persistence (hibernate) error because IOUState isn't registered with persistence layer.

The stacktrace from com.example.flow.IOUFlowTests.signedTransactionReturnedByTheFlowIsSignedByTheAcceptor is below:

```
[WARN] 16:17:04,601 [Mock network] flow.[70d57617-e770-4e94-8a73-086038757e9c].run - Terminated by unexpected exception
 java.lang.IllegalArgumentException: Unknown entity: com.example.schema.IOUSchemaV1$PersistentIOU
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:777) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:758) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at net.corda.node.services.schema.PersistentStateService.persistStatesWithSchema$node(PersistentStateService.kt:49) ~[corda-node-3.3-corda.jar:?]
	at net.corda.node.services.schema.PersistentStateService.persist(PersistentStateService.kt:41) ~[corda-node-3.3-corda.jar:?]
	at net.corda.node.services.vault.NodeVaultService.processAndNotify(NodeVaultService.kt:216) ~[corda-node-3.3-corda.jar:?]
	at net.corda.node.services.vault.NodeVaultService.access$processAndNotify(NodeVaultService.kt:49) ~[corda-node-3.3-corda.jar:?]
	at net.corda.node.services.vault.NodeVaultService$notifyAll$1.invoke(NodeVaultService.kt:120) ~[corda-node-3.3-corda.jar:?]
	at net.corda.node.services.vault.NodeVaultService.notifyAll(NodeVaultService.kt:130) ~[corda-node-3.3-corda.jar:?]
	at net.corda.node.services.api.ServiceHubInternal$DefaultImpls.recordTransactions(ServiceHubInternal.kt:118) ~[corda-node-3.3-corda.jar:?]
	at net.corda.node.internal.AbstractNode$ServiceHubInternalImpl$recordTransactions$1.invoke(AbstractNode.kt:876) ~[corda-node-3.3-corda.jar:?]
	at net.corda.node.internal.AbstractNode$ServiceHubInternalImpl$recordTransactions$1.invoke(AbstractNode.kt:836) ~[corda-node-3.3-corda.jar:?]
	at net.corda.nodeapi.internal.persistence.CordaPersistence.transaction(CordaPersistence.kt:136) ~[corda-node-api-3.3-corda.jar:?]
	at net.corda.nodeapi.internal.persistence.CordaPersistence.transaction(CordaPersistence.kt:124) ~[corda-node-api-3.3-corda.jar:?]
	at net.corda.nodeapi.internal.persistence.CordaPersistence.transaction(CordaPersistence.kt:131) ~[corda-node-api-3.3-corda.jar:?]
	at net.corda.node.internal.AbstractNode$ServiceHubInternalImpl.recordTransactions(AbstractNode.kt:875) ~[corda-node-3.3-corda.jar:?]
	at net.corda.core.node.ServiceHub$DefaultImpls.recordTransactions(ServiceHub.kt:201) ~[corda-core-3.3-corda.jar:?]
	at net.corda.node.services.api.ServiceHubInternal$DefaultImpls.recordTransactions(ServiceHubInternal.kt) ~[corda-node-3.3-corda.jar:?]
	at net.corda.node.internal.AbstractNode$ServiceHubInternalImpl.recordTransactions(AbstractNode.kt:836) ~[corda-node-3.3-corda.jar:?]
	at net.corda.core.node.ServiceHub$DefaultImpls.recordTransactions(ServiceHub.kt:193) ~[corda-core-3.3-corda.jar:?]
	at net.corda.node.services.api.ServiceHubInternal$DefaultImpls.recordTransactions(ServiceHubInternal.kt) ~[corda-node-3.3-corda.jar:?]
	at net.corda.node.internal.AbstractNode$ServiceHubInternalImpl.recordTransactions(AbstractNode.kt:836) ~[corda-node-3.3-corda.jar:?]
	at net.corda.core.flows.FinalityFlow.notariseAndRecord(FinalityFlow.kt:78) ~[corda-core-3.3-corda.jar:?]
	at net.corda.core.flows.FinalityFlow.call(FinalityFlow.kt:56) ~[corda-core-3.3-corda.jar:?]
	at net.corda.core.flows.FinalityFlow.call(FinalityFlow.kt:28) ~[corda-core-3.3-corda.jar:?]
	at net.corda.core.flows.FlowLogic.subFlow(FlowLogic.kt:290) ~[corda-core-3.3-corda.jar:?]
	at com.example.flow.ExampleFlow$Initiator.call(ExampleFlow.java:118) ~[main/:?]
	at com.example.flow.ExampleFlow$Initiator.call(ExampleFlow.java:33) ~[main/:?]
	at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:96) [corda-node-3.3-corda.jar:?]
	at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:44) [corda-node-3.3-corda.jar:?]
	at co.paralleluniverse.fibers.Fiber.run1(Fiber.java:1092) [quasar-core-0.7.9-jdk8.jar:0.7.9]
	at co.paralleluniverse.fibers.Fiber.exec(Fiber.java:788) [quasar-core-0.7.9-jdk8.jar:0.7.9]
	at co.paralleluniverse.fibers.RunnableFiberTask.doExec(RunnableFiberTask.java:100) [quasar-core-0.7.9-jdk8.jar:0.7.9]
	at co.paralleluniverse.fibers.RunnableFiberTask.run(RunnableFiberTask.java:91) [quasar-core-0.7.9-jdk8.jar:0.7.9]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at net.corda.node.utilities.AffinityExecutor$ServiceAffinityExecutor$1$thread$1.run(AffinityExecutor.kt:62) [corda-node-3.3-corda.jar:?]
```

The other tests fail with similar exceptions

Proposed fix is in #158 pull request

**Comment by ASitnikov** [comment]
This is issue was fixed in 346176159660d8723f53f2fb3438d5b34dfbd5db
